# Generated by Django 4.2.5 on 2023-10-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projects_risk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectissues',
            name='category',
        ),
    ]
