# Generated by Django 4.2.5 on 2023-11-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_projectissues_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectissues',
            name='created_in_backlog',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='projectissues',
            name='resolution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
