# Generated by Django 4.2.5 on 2023-11-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_projectissues_created_in_backlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
