# Generated by Django 4.2.5 on 2023-11-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_projectissues_created_in_backlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='risk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
