# Generated by Django 4.2.5 on 2023-11-17 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0007_alter_projects_risk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projects",
            name="issue_count",
        ),
    ]
