# Generated by Django 4.2.5 on 2023-10-13 08:31

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.IntegerField()),
                ('result', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(default=None, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'active'), (2, 'inactive')])),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'batch_process',
            },
        ),
        migrations.CreateModel(
            name='BrowserCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_chrome_latest', models.PositiveSmallIntegerField(choices=[(1, 'pass'), (2, 'fail')], null=True)),
                ('microsoft_edge_latest', models.PositiveSmallIntegerField(choices=[(1, 'pass'), (2, 'fail')], null=True)),
                ('mac_safari_latest', models.PositiveSmallIntegerField(choices=[(1, 'pass'), (2, 'fail')], null=True)),
                ('mac_chrome_latest', models.PositiveSmallIntegerField(choices=[(1, 'pass'), (2, 'fail')], null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'inactive'), (1, 'Active')], null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'browser_compatibility',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=50, null=True)),
                ('number_of_testcases', models.IntegerField(null=True)),
                ('executed_testcases_count', models.IntegerField(null=True)),
                ('passed_testcases_count', models.IntegerField(null=True)),
                ('failed_testcases_count', models.IntegerField(null=True)),
                ('not_tested_count', models.IntegerField(null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'summary',
            },
        ),
        migrations.CreateModel(
            name='TestcaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, null=True)),
                ('date_of_release', models.DateField(null=True)),
                ('prepared_by', models.CharField(max_length=50, null=True)),
                ('reviewed_by', models.CharField(max_length=50, null=True)),
                ('approved_by', models.CharField(max_length=50, null=True)),
                ('change_description', models.TextField(blank=True, max_length=255, null=True)),
                ('sheet_name', models.CharField(max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'testcase_result',
            },
        ),
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case_id', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(max_length=255, null=True)),
                ('feature', models.CharField(max_length=50, null=True)),
                ('sub_feature', models.CharField(max_length=50, null=True)),
                ('test_steps', models.TextField(max_length=255, null=True)),
                ('pre_condition', models.TextField(max_length=255, null=True)),
                ('expected_results', models.TextField(max_length=255, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('sheet_name', models.CharField(blank=True, max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('comments', models.TextField(null=True)),
                ('browser_compatibility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_cases_browser_compatibility', to='report.browsercompatibility')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.projects')),
                ('project_issues', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.projectissues')),
            ],
            options={
                'db_table': 'test_cases',
            },
        ),
        migrations.CreateModel(
            name='Sweep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_result', models.TextField(null=True)),
                ('build', models.CharField(max_length=50, null=True)),
                ('swipe_count', models.IntegerField(null=True)),
                ('swipe_status', models.CharField(max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('test_cases', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sweep_test_cases', to='report.testcases')),
            ],
            options={
                'db_table': 'sweep',
            },
        ),
    ]
