# Generated by Django 4.2.5 on 2023-10-26 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_projectissues_category'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sweep',
            old_name='swipe_status',
            new_name='sweep_status',
        ),
        migrations.RemoveField(
            model_name='sweep',
            name='swipe_count',
        ),
        migrations.AddField(
            model_name='summary',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.projects'),
        ),
        migrations.AddField(
            model_name='sweep',
            name='bug_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sweep',
            name='sweep_count',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcaseresult',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.projects'),
        ),
        migrations.AlterField(
            model_name='testcaseresult',
            name='version',
            field=models.FloatField(null=True),
        ),
    ]
