# Generated by Django 4.2.5 on 2023-11-02 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_projectissues_category'),
        ('report', '0002_rename_swipe_status_sweep_sweep_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sweep',
            name='bug_id',
        ),
        migrations.AlterField(
            model_name='summary',
            name='project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.projects'),
        ),
        migrations.AlterField(
            model_name='sweep',
            name='build',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sweep',
            name='sweep_count',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testcaseresult',
            name='approved_by',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testcaseresult',
            name='prepared_by',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testcaseresult',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.projects'),
        ),
        migrations.AlterField(
            model_name='testcaseresult',
            name='reviewed_by',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testcaseresult',
            name='sheet_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testcaseresult',
            name='version',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='category',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='feature',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='sub_feature',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='test_case_id',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SweepBugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_id', models.TextField(max_length=255, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('sweep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.sweep')),
            ],
            options={
                'db_table': 'sweep_bugs',
            },
        ),
    ]
