# Generated by Django 4.2.5 on 2023-11-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_remove_sweep_bug_id_alter_summary_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcases',
            name='test_case_choice',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
