# Generated by Django 4.2.5 on 2023-11-09 18:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0004_testcases_test_case_choice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batchprocess",
            name="batch_id",
        ),
        migrations.RemoveField(
            model_name="batchprocess",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="batchprocess",
            name="result",
        ),
        migrations.RemoveField(
            model_name="batchprocess",
            name="start_time",
        ),
        migrations.AddField(
            model_name="batchprocess",
            name="name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name="SubBatchProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "active"), (2, "inactive")]
                    ),
                ),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                (
                    "batch_process",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="report.batchprocess",
                    ),
                ),
            ],
            options={
                "db_table": "sub_batch_process",
            },
        ),
    ]
