# Generated by Django 4.2.2 on 2023-11-08 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_projects_start_date'),
        ('report', '0004_testcases_test_case_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseDateAndCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excuted_test_case_count', models.IntegerField(null=True)),
                ('passed_test_case_count', models.ImageField(null=True, upload_to='')),
                ('date_of_executiion', models.DateField(null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.projects')),
            ],
            options={
                'db_table': 'test_case_date_count',
            },
        ),
    ]
