# Generated by Django 4.2.2 on 2023-11-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_testcasedateandcount_passed_test_case_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasedateandcount',
            name='test_case_choice',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
