# Generated by Django 4.2.5 on 2023-11-10 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0006_alter_batchprocess_create_date_and_more"),
        ("report", "0007_testcasedateandcount_test_case_choice"),
    ]

    operations = []
