# Generated by Django 4.2.5 on 2023-11-10 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0006_alter_projectissues_created_in_backlog"),
        ("report", "0008_merge_20231110_1306"),
    ]

    operations = [
        migrations.CreateModel(
            name="BugSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("open_bugs", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "active"), (2, "inactive")]
                    ),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("update_date", models.DateTimeField(auto_now=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.projects",
                    ),
                ),
            ],
            options={
                "db_table": "bug_summary",
            },
        ),
    ]
